laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('neovalor', 'NeovalorController@index')->name('neovalor');
    Route::get('neovalor/curriculo', 'NeovalorController@indexCurriculo')->name('curriculo');
    Route::get('consultoria', 'ConsultoriaController@index')->name('consultoria');
    Route::get('clientes-e-projetos', 'ClientesProjetosController@index')->name('clientes-e-projetos');
    Route::get('educacao-corporativa', 'ImersaoController@index')->name('imersao'); // alterou nome para EDUCAÇÃO CORPORATIVA
    Route::get('neolabx', 'NeolabxController@index')->name('neolabx');
    Route::get('neolabx/rede-de-consultores', 'NeolabxController@indexRede')->name('neolabx.rede');
    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{artigo}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('home/contadores', 'ContadoresHomeController', ['only' => ['index', 'update']]);
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('expertises', 'ExpertisesController');
        Route::resource('curriculo', 'CurriculoController', ['only' => ['index', 'update']]);
        Route::resource('consultoria', 'ConsultoriaController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController');
        Route::resource('consultoria/informacoes', 'ConsultoriaInformacoesController');
        Route::resource('clientes-e-projetos', 'ClientesProjetosController', ['only' => ['index', 'update']]);
        Route::resource('clientes-e-projetos/contadores', 'ContadoresProjetosController', ['only' => ['index', 'update']]);
        Route::resource('grupos-experiencias', 'GruposExperienciasController');
        Route::resource('experiencias', 'ExperienciasController');
        Route::resource('treinamentos', 'TreinamentosController');
        Route::resource('imersao', 'ImersaoDadosController', ['only' => ['index', 'update']]);
        Route::resource('imersoes', 'ImersoesController');
        Route::resource('imersao/informacoes', 'ImersaoInformacoesController');
        Route::resource('neolabx', 'NeolabxController', ['only' => ['index', 'update']]);
        Route::resource('neolabx/inovacao', 'NeolabxInovacaoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('neolabx/consultores', 'NeolabxConsultoresController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog/artigos', 'BlogArtigosController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function() {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Models/Treinamento.php
<?php

namespace App\Models;

use App\Helpers\CropImage;
use Illuminate\Database\Eloquent\Model;

class Treinamento extends Model
{
    protected $table = 'treinamentos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public static function upload_imagem()
    {
        return CropImage::make('imagem', [
            'width'  => 120,
            'height' => null,
            'path'   => 'assets/img/treinamentos/'
        ]);
    }
}

laravel/app/Http/Controllers/Painel/TreinamentosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\TreinamentosRequest;
use App\Models\Treinamento;

class TreinamentosController extends Controller
{
    public function index()
    {
        $treinamentos = Treinamento::ordenados()->get();

        return view('painel.clientes-e-projetos.treinamentos.index', compact('treinamentos'));
    }

    public function create()
    {
        return view('painel.clientes-e-projetos.treinamentos.create');
    }

    public function store(TreinamentosRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Treinamento::upload_imagem();

            Treinamento::create($input);

            return redirect()->route('painel.treinamentos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Treinamento $treinamento)
    {
        return view('painel.clientes-e-projetos.treinamentos.edit', compact('treinamento'));
    }

    public function update(TreinamentosRequest $request, Treinamento $treinamento)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Treinamento::upload_imagem();

            $treinamento->update($input);

            return redirect()->route('painel.treinamentos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Treinamento $treinamento)
    {
        try {
            $treinamento->delete();

            return redirect()->route('painel.treinamentos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/clientes-e-projetos/treinamentos/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>CLIENTES E PROJETOS - Treinamentos |</small> Adicionar Treinamento</h2>
</legend>

{!! Form::open(['route' => 'painel.treinamentos.store', 'files' => true]) !!}

@include('painel.clientes-e-projetos.treinamentos.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/clientes-e-projetos/treinamentos/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>CLIENTES E PROJETOS - Treinamentos |</small> Editar Treinamento</h2>
</legend>

{!! Form::model($treinamento, [
'route' => ['painel.treinamentos.update', $treinamento->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.clientes-e-projetos.treinamentos.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/clientes-e-projetos/treinamentos/form.blade.php
@include('painel.common.flash')

<div class="well form-group">
    {!! Form::label('imagem', 'Logo Empresa') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/treinamentos/'.$treinamento->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('empresa', 'Empresa') !!}
    {!! Form::text('empresa', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('ano', 'Ano') !!}
    {!! Form::text('ano', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('tipo', 'Tipo') !!}
    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título do Treinamento') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('consultor', 'Consultor') !!}
    {!! Form::text('consultor', null, ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.treinamentos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/clientes-e-projetos/treinamentos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        CLIENTES E PROJETOS - Treinamentos
        <a href="{{ route('painel.treinamentos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Treinamento</a>
    </h2>
</legend>


@if(!count($treinamentos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="treinamentos">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Logo Empresa</th>
            <th>Ano</th>
            <th>Título</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($treinamentos as $treinamento)
        <tr class="tr-row" id="{{ $treinamento->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td><img src="{{ asset('assets/img/treinamentos/'.$treinamento->imagem) }}" style="width: 100%; max-width:100px;" alt=""></td>
            <td>{{ $treinamento->ano }}</td>
            <td>{{ $treinamento->titulo }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.treinamentos.destroy', $treinamento->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.treinamentos.edit', $treinamento->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection