laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('neovalor', 'NeovalorController@index')->name('neovalor');
    Route::get('neovalor/curriculo', 'NeovalorController@indexCurriculo')->name('curriculo');
    Route::get('consultoria', 'ConsultoriaController@index')->name('consultoria');
    Route::get('clientes-e-projetos', 'ClientesProjetosController@index')->name('clientes-e-projetos');
    Route::get('educacao-corporativa', 'ImersaoController@index')->name('imersao'); // alterou nome para EDUCAÇÃO CORPORATIVA
    Route::get('neolabx', 'NeolabxController@index')->name('neolabx');
    Route::get('neolabx/rede-de-consultores', 'NeolabxController@indexRede')->name('neolabx.rede');
    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{artigo}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('home/contadores', 'ContadoresHomeController', ['only' => ['index', 'update']]);
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('expertises', 'ExpertisesController');
        Route::resource('curriculo', 'CurriculoController', ['only' => ['index', 'update']]);
        Route::resource('consultoria', 'ConsultoriaController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController');
        Route::resource('consultoria/informacoes', 'ConsultoriaInformacoesController');
        Route::resource('clientes-e-projetos', 'ClientesProjetosController', ['only' => ['index', 'update']]);
        Route::resource('clientes-e-projetos/contadores', 'ContadoresProjetosController', ['only' => ['index', 'update']]);
        Route::resource('grupos-experiencias', 'GruposExperienciasController');
        Route::resource('experiencias', 'ExperienciasController');
        Route::resource('treinamentos', 'TreinamentosController');
        Route::resource('imersao', 'ImersaoDadosController', ['only' => ['index', 'update']]);
        Route::resource('imersoes', 'ImersoesController');
        Route::resource('imersao/informacoes', 'ImersaoInformacoesController');
        Route::resource('neolabx', 'NeolabxController', ['only' => ['index', 'update']]);
        Route::resource('neolabx/inovacao', 'NeolabxInovacaoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('neolabx/consultores', 'NeolabxConsultoresController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog/artigos', 'BlogArtigosController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function() {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Models/Consultoria.php
<?php

namespace App\Models;

use App\Helpers\CropImage;
use Illuminate\Database\Eloquent\Model;

class Consultoria extends Model
{
    protected $table = 'consultoria';

    protected $guarded = ['id'];

    public static function upload_capa()
    {
        return CropImage::make('capa', [
            'width'  => 1980,
            'height' => null,
            'path'   => 'assets/img/consultoria/'
        ]);
    }
}

laravel/app/Http/Controllers/ConsultoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Consultoria;
use App\Models\ConsultoriaInformacao;
use App\Models\Projeto;

class ConsultoriaController extends Controller
{
    public function index()
    {
        $dados = Consultoria::first();
        $projetos = Projeto::where('novidade', 0)->ordenados()->get();
        $projetosNovidades = Projeto::novidades()->ordenados()->get();
        $infosExtras = ConsultoriaInformacao::ordenados()->get();

        return view('frontend.consultoria', compact('dados', 'projetos', 'projetosNovidades', 'infosExtras'));
    }
}

laravel/app/Http/Controllers/Painel/ConsultoriaController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConsultoriaRequest;
use App\Models\Consultoria;

class ConsultoriaController extends Controller
{
    public function index()
    {
        $registro = Consultoria::first();

        return view('painel.consultoria.dados.edit', compact('registro'));
    }

    public function update(ConsultoriaRequest $request, Consultoria $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Consultoria::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.consultoria.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/consultoria/informacoes/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>CONSULTORIA - Informações Extras |</small> Adicionar Informação</h2>
</legend>

{!! Form::open(['route' => 'painel.consultoria.informacoes.store', 'files' => true]) !!}

@include('painel.consultoria.informacoes.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/consultoria/informacoes/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>CONSULTORIA - Informações Extras |</small> Editar Informação</h2>
</legend>

{!! Form::model($info, [
'route' => ['painel.consultoria.informacoes.update', $info->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.consultoria.informacoes.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/consultoria/informacoes/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control ckeditor', 'data-editor' => 'textImg']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.consultoria.informacoes.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/consultoria/informacoes/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        CONSULTORIA - Informações Extras
        <a href="{{ route('painel.consultoria.informacoes.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Informação</a>
    </h2>
</legend>


@if(!count($infos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="consultoria_informacoes">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Título</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($infos as $info)
        <tr class="tr-row" id="{{ $info->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td>{{ $info->titulo }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.consultoria.informacoes.destroy', $info->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.consultoria.informacoes.edit', $info->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection