laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('neovalor', 'NeovalorController@index')->name('neovalor');
    Route::get('neovalor/curriculo', 'NeovalorController@indexCurriculo')->name('curriculo');
    Route::get('consultoria', 'ConsultoriaController@index')->name('consultoria');
    Route::get('clientes-e-projetos', 'ClientesProjetosController@index')->name('clientes-e-projetos');
    Route::get('educacao-corporativa', 'ImersaoController@index')->name('imersao'); // alterou nome para EDUCAÇÃO CORPORATIVA
    Route::get('neolabx', 'NeolabxController@index')->name('neolabx');
    Route::get('neolabx/rede-de-consultores', 'NeolabxController@indexRede')->name('neolabx.rede');
    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{artigo}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('home/contadores', 'ContadoresHomeController', ['only' => ['index', 'update']]);
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('expertises', 'ExpertisesController');
        Route::resource('curriculo', 'CurriculoController', ['only' => ['index', 'update']]);
        Route::resource('consultoria', 'ConsultoriaController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController');
        Route::resource('consultoria/informacoes', 'ConsultoriaInformacoesController');
        Route::resource('clientes-e-projetos', 'ClientesProjetosController', ['only' => ['index', 'update']]);
        Route::resource('clientes-e-projetos/contadores', 'ContadoresProjetosController', ['only' => ['index', 'update']]);
        Route::resource('grupos-experiencias', 'GruposExperienciasController');
        Route::resource('experiencias', 'ExperienciasController');
        Route::resource('treinamentos', 'TreinamentosController');
        Route::resource('imersao', 'ImersaoDadosController', ['only' => ['index', 'update']]);
        Route::resource('imersoes', 'ImersoesController');
        Route::resource('imersao/informacoes', 'ImersaoInformacoesController');
        Route::resource('neolabx', 'NeolabxController', ['only' => ['index', 'update']]);
        Route::resource('neolabx/inovacao', 'NeolabxInovacaoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('neolabx/consultores', 'NeolabxConsultoresController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog/artigos', 'BlogArtigosController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function() {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BannersRequest;
use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.home.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.home.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.home.banners.edit', compact('banner'));
    }

    public function update(BannersRequest $request, Banner $banner)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $banner->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $banner)
    {
        try {
            $banner->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BlogArtigosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogArtigosRequest;
use App\Models\BlogArtigo;
use App\Models\BlogCategoria;

class BlogArtigosController extends Controller
{
    public function index()
    {
        $categorias = BlogCategoria::ordenados()->get();

        if (isset($_GET['categoria'])) {
            $categoria = $_GET['categoria'];
            $artigos = BlogArtigo::categoria($categoria)->orderBy('data', 'desc')->get();
        } else {
            $artigos = BlogArtigo::orderBy('data', 'desc')->get();
        }

        return view('painel.blog.artigos.index', compact('artigos', 'categorias'));
    }

    public function create()
    {
        $categorias = BlogCategoria::ordenados()->pluck('titulo', 'id');

        return view('painel.blog.artigos.create', compact('categorias'));
    }

    public function store(BlogArtigosRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            if (isset($input['capa'])) $input['capa'] = BlogArtigo::upload_capa();

            $count = count(BlogArtigo::where('slug', $input['slug'])->where('categoria_id', $input['categoria_id'])->get());

            if ($count == 0) {
                BlogArtigo::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se esse registro já existe']);
            }

            return redirect()->route('painel.blog.artigos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit($artigo_id)
    {
        $artigo = BlogArtigo::where('id', $artigo_id)->first();
        $categorias = BlogCategoria::ordenados()->pluck('titulo', 'id');

        return view('painel.blog.artigos.edit', compact('artigo', 'categorias'));
    }

    public function update(BlogArtigosRequest $request, $artigo_id)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $artigo = BlogArtigo::where('id', $artigo_id)->first();

            if (isset($input['capa'])) $input['capa'] = BlogArtigo::upload_capa();

            $artigo->update($input);

            return redirect()->route('painel.blog.artigos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy($artigo_id)
    {
        try {
            $artigo = BlogArtigo::where('id', $artigo_id)->first();
            $artigo->delete();

            return redirect()->route('painel.blog.artigos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BlogCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogCategoriasRequest;
use App\Models\BlogCategoria;

class BlogCategoriasController extends Controller
{
    public function index()
    {
        $categorias = BlogCategoria::ordenados()->get();

        return view('painel.blog.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.blog.categorias.create');
    }

    public function store(BlogCategoriasRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $count = count(BlogCategoria::where('slug', $input['slug'])->get());

            if ($count == 0) {
                BlogCategoria::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se esse registro já existe']);
            }

            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit($categoria_id)
    {
        $categoria = BlogCategoria::where('id', $categoria_id)->first();

        return view('painel.blog.categorias.edit', compact('categoria'));
    }

    public function update(BlogCategoriasRequest $request, $categoria_id)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $categoria = BlogCategoria::where('id', $categoria_id)->first();

            $categoria->update($input);

            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy($categoria_id)
    {
        try {
            $categoria = BlogCategoria::where('id', $categoria_id)->first();

            $categoria->delete();

            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ClientesProjetosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClientesProjetosRequest;
use App\Models\ClienteProjeto;

class ClientesProjetosController extends Controller
{
    public function index()
    {
        $registro = ClienteProjeto::first();

        return view('painel.clientes-e-projetos.dados.edit', compact('registro'));
    }

    public function update(ClientesProjetosRequest $request, $registro_id)
    {
        try {
            $input = $request->all();

            $registro = ClienteProjeto::where('id', $registro_id)->first();

            if (isset($input['capa'])) $input['capa'] = ClienteProjeto::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.clientes-e-projetos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConsultoriaController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConsultoriaRequest;
use App\Models\Consultoria;

class ConsultoriaController extends Controller
{
    public function index()
    {
        $registro = Consultoria::first();

        return view('painel.consultoria.dados.edit', compact('registro'));
    }

    public function update(ConsultoriaRequest $request, Consultoria $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Consultoria::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.consultoria.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContadoresHomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContadoresHomeRequest;
use App\Models\ContadorHome;

class ContadoresHomeController extends Controller
{
    public function index()
    {
        $registro = ContadorHome::first();

        return view('painel.home.contadores.edit', compact('registro'));
    }

    public function update(ContadoresHomeRequest $request, $registro_id)
    {
        try {
            $input = $request->all();

            $registro = ContadorHome::where('id', $registro_id)->first();
            
            $registro->update($input);

            return redirect()->route('painel.home.contadores.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
<div class="alert alert-block alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {!! session('success') !!}
</div>
@endif

@if($errors->any())
<div class="alert alert-block alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    @foreach($errors->all() as $error)
    {!! $error !!}<br>
    @endforeach
</div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica-de-privacidade*', 'painel.aceite-de-cookies*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}" class="link-nav-painel">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li class="dropdown @if(Tools::routeIs(['painel.banners*', 'painel.home*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.home.index')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>
            <li @if(Tools::routeIs('painel.home.contadores*')) class="active" @endif>
                <a href="{{ route('painel.home.contadores.index') }}">Contadores</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.empresa*', 'painel.expertises*', 'painel.curriculo*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Neovalor <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.empresa*')) class="active" @endif>
                <a href="{{ route('painel.empresa.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.expertises*')) class="active" @endif>
                <a href="{{ route('painel.expertises.index') }}">Expertises</a>
            </li>
            <li @if(Tools::routeIs('painel.curriculo*')) class="active" @endif>
                <a href="{{ route('painel.curriculo.index') }}">Currículo</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.consultoria*', 'painel.projetos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consultoria <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs(['painel.consultoria.index', 'painel.consultoria.create' , 'painel.consultoria.edit' ])) class="active" @endif>
                <a href="{{ route('painel.consultoria.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.projetos*')) class="active" @endif>
                <a href="{{ route('painel.projetos.index') }}">Projetos</a>
            </li>
            <li @if(Tools::routeIs('painel.consultoria.informacoes*')) class="active" @endif>
                <a href="{{ route('painel.consultoria.informacoes.index') }}">Informações Extras</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.clientes-e-projetos*', 'painel.grupos-experiencias*', 'painel.experiencias*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clientes e Projetos <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.clientes-e-projetos.index')) class="active" @endif>
                <a href="{{ route('painel.clientes-e-projetos.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.clientes-e-projetos.contadores*')) class="active" @endif>
                <a href="{{ route('painel.clientes-e-projetos.contadores.index') }}">Contadores</a>
            </li>
            <li @if(Tools::routeIs('painel.grupos-experiencias*')) class="active" @endif>
                <a href="{{ route('painel.grupos-experiencias.index') }}">Grupos de Experiências</a>
            </li>
            <li @if(Tools::routeIs('painel.experiencias*')) class="active" @endif>
                <a href="{{ route('painel.experiencias.index') }}">Experiências</a>
            </li>
            <li @if(Tools::routeIs('painel.treinamentos*')) class="active" @endif>
                <a href="{{ route('painel.treinamentos.index') }}">Treinamentos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.imersao*', 'painel.imersoes*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Educação Corporativa <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.imersao.index')) class="active" @endif>
                <a href="{{ route('painel.imersao.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.imersoes*')) class="active" @endif>
                <a href="{{ route('painel.imersoes.index') }}">Imersões</a>
            </li>
            <li @if(Tools::routeIs('painel.imersao.informacoes*')) class="active" @endif>
                <a href="{{ route('painel.imersao.informacoes.index') }}">Informações Extras</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.neolabx*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">NeoLabX <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.neolabx.index')) class="active" @endif>
                <a href="{{ route('painel.neolabx.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.neolabx.inovacao*')) class="active" @endif>
                <a href="{{ route('painel.neolabx.inovacao.index') }}">Inovação</a>
            </li>
            <li @if(Tools::routeIs('painel.neolabx.consultores*')) class="active" @endif>
                <a href="{{ route('painel.neolabx.consultores.index') }}">Rede de Consultores</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.blog*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.blog.categorias*')) class="active" @endif>
                <a href="{{ route('painel.blog.categorias.index') }}">Categorias</a>
            </li>
            <li @if(Tools::routeIs('painel.blog.artigos*')) class="active" @endif>
                <a href="{{ route('painel.blog.artigos.index') }}">Artigos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>

<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>

</body>

</html>