laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('neovalor', 'NeovalorController@index')->name('neovalor');
    Route::get('neovalor/curriculo', 'NeovalorController@indexCurriculo')->name('curriculo');
    Route::get('consultoria', 'ConsultoriaController@index')->name('consultoria');
    Route::get('clientes-e-projetos', 'ClientesProjetosController@index')->name('clientes-e-projetos');
    Route::get('educacao-corporativa', 'ImersaoController@index')->name('imersao'); // alterou nome para EDUCAÇÃO CORPORATIVA
    Route::get('neolabx', 'NeolabxController@index')->name('neolabx');
    Route::get('neolabx/rede-de-consultores', 'NeolabxController@indexRede')->name('neolabx.rede');
    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{artigo}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('home/contadores', 'ContadoresHomeController', ['only' => ['index', 'update']]);
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('expertises', 'ExpertisesController');
        Route::resource('curriculo', 'CurriculoController', ['only' => ['index', 'update']]);
        Route::resource('consultoria', 'ConsultoriaController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController');
        Route::resource('consultoria/informacoes', 'ConsultoriaInformacoesController');
        Route::resource('clientes-e-projetos', 'ClientesProjetosController', ['only' => ['index', 'update']]);
        Route::resource('clientes-e-projetos/contadores', 'ContadoresProjetosController', ['only' => ['index', 'update']]);
        Route::resource('grupos-experiencias', 'GruposExperienciasController');
        Route::resource('experiencias', 'ExperienciasController');
        Route::resource('treinamentos', 'TreinamentosController');
        Route::resource('imersao', 'ImersaoDadosController', ['only' => ['index', 'update']]);
        Route::resource('imersoes', 'ImersoesController');
        Route::resource('imersao/informacoes', 'ImersaoInformacoesController');
        Route::resource('neolabx', 'NeolabxController', ['only' => ['index', 'update']]);
        Route::resource('neolabx/inovacao', 'NeolabxInovacaoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('neolabx/consultores', 'NeolabxConsultoresController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog/artigos', 'BlogArtigosController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function() {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\BlogArtigo;
use App\Models\BlogCategoria;

class BlogController extends Controller
{
    public function index()
    {
        $categorias = BlogCategoria::ordenados()->get();

        if (isset($_GET['categoria'])) {

            $categoria = $_GET['categoria'];
            $destaque = BlogArtigo::join('blog_categorias', 'blog_categorias.id', '=', 'blog_artigos.categoria_id')
                ->select('blog_categorias.id as categoria_id', 'blog_categorias.titulo as categoria_titulo', 'blog_categorias.slug as categoria_slug', 'blog_artigos.id', 'blog_artigos.capa', 'blog_artigos.slug', 'blog_artigos.titulo', 'blog_artigos.autor', 'blog_artigos.data')
                ->where('blog_categorias.slug', $categoria)
                ->orderBy('data', 'desc')->first();
            $artigos = BlogArtigo::join('blog_categorias', 'blog_categorias.id', '=', 'blog_artigos.categoria_id')
                ->select('blog_categorias.id as categoria_id', 'blog_categorias.titulo as categoria_titulo', 'blog_categorias.slug as categoria_slug', 'blog_artigos.id', 'blog_artigos.capa', 'blog_artigos.slug', 'blog_artigos.titulo', 'blog_artigos.autor', 'blog_artigos.data')
                ->where('blog_categorias.slug', $categoria)
                ->orderBy('blog_artigos.data', 'desc')->skip(1)->take(PHP_INT_MAX)->get();
            
        } else {

            $destaque = BlogArtigo::join('blog_categorias', 'blog_categorias.id', '=', 'blog_artigos.categoria_id')
                ->select('blog_categorias.id as categoria_id', 'blog_categorias.titulo as categoria_titulo', 'blog_categorias.slug as categoria_slug', 'blog_artigos.id', 'blog_artigos.capa', 'blog_artigos.slug', 'blog_artigos.titulo', 'blog_artigos.autor', 'blog_artigos.data')
                ->orderBy('data', 'desc')->first();
            $artigos = BlogArtigo::join('blog_categorias', 'blog_categorias.id', '=', 'blog_artigos.categoria_id')
                ->select('blog_categorias.id as categoria_id', 'blog_categorias.titulo as categoria_titulo', 'blog_categorias.slug as categoria_slug', 'blog_artigos.id', 'blog_artigos.capa', 'blog_artigos.slug', 'blog_artigos.titulo', 'blog_artigos.autor', 'blog_artigos.data')
                ->orderBy('blog_artigos.data', 'desc')->skip(1)->take(PHP_INT_MAX)->get();
        }

        return view('frontend.blog', compact('categorias', 'destaque', 'artigos'));
    }

    public function show($slug)
    {
        $categorias = BlogCategoria::ordenados()->get();

        $artigo = BlogArtigo::join('blog_categorias', 'blog_categorias.id', '=', 'blog_artigos.categoria_id')
            ->select('blog_categorias.id as categoria_id', 'blog_categorias.titulo as categoria_titulo', 'blog_categorias.slug as categoria_slug', 'blog_artigos.id', 'blog_artigos.capa', 'blog_artigos.slug', 'blog_artigos.titulo', 'blog_artigos.autor', 'blog_artigos.data', 'blog_artigos.texto')
            ->where('blog_artigos.slug', $slug)->first();

        return view('frontend.blog-show', compact('categorias', 'artigo'));
    }
}

laravel/resources/views/painel/blog/artigos/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>BLOG - Artigos |</small> Adicionar Artigo</h2>
</legend>

{!! Form::open(['route' => 'painel.blog.artigos.store', 'files' => true]) !!}

@include('painel.blog.artigos.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/blog/artigos/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>BLOG - Artigos |</small> Editar Artigo</h2>
</legend>

{!! Form::model($artigo, [
'route' => ['painel.blog.artigos.update', $artigo->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.blog.artigos.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/blog/artigos/form.blade.php
@include('painel.common.flash')

<div class="well">
    <div class="checkbox" style="margin:0">
        <label style="font-weight:bold">
            {!! Form::hidden('neolabx', 0) !!}
            {!! Form::checkbox('neolabx') !!}
            NeoLabX
        </label>
    </div>
</div>

<div class="form-group">
    {!! Form::label('categoria_id', 'Categoria') !!}
    {!! Form::select('categoria_id', $categorias , old('categoria_id'), ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('data', 'Data') !!}
    {!! Form::date('data', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('autor', 'Autor') !!}
    {!! Form::text('autor', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control ckeditor', 'data-editor' => 'padrao']) !!}
</div>

<div class="well form-group">
    {!! Form::label('capa', 'Capa') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/blog/'.$artigo->capa) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('capa', ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.blog.artigos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/blog/artigos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        BLOG - Artigos
        <a href="{{ route('painel.blog.artigos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Artigo</a>
    </h2>
</legend>

<h4 class="titulo-filtro">Categorias:</h4>
<div class="lista-filtro">
    <a href="{{ route('painel.blog.artigos.index') }}" class="item">Todos</a>
    @foreach($categorias as $categoria)
    <a href="{{ route('painel.blog.artigos.index', ['categoria' => $categoria->id]) }}" class="item {{ (isset($_GET['categoria']) && $_GET['categoria'] == $categoria->id) ? 'active' : '' }}">{{ $categoria->titulo }}</a>
    @endforeach
</div>

@if(!count($artigos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="blog_artigos">
    <thead>
        <tr>
            <th>Data</th>
            <th>Capa</th>
            <th>Título</th>
            <th>Categoria</th>
            <th>NeoLabX</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($artigos as $artigo)
        <tr class="tr-row" id="{{ $artigo->id }}">
            <td>{{ strftime("%d/%m/%Y", strtotime($artigo->data)) }}</td>
            <td><img src="{{ asset('assets/img/blog/'.$artigo->capa) }}" style="width: 100%; max-width:80px;" alt=""></td>
            <td>{{ $artigo->titulo }}</td>
            @php
            $categoria = $categorias->find($artigo->categoria_id)->titulo;
            @endphp
            <td>{{ $categoria }}</td>
            <td style="text-align: center;">
                <span class="glyphicon {{ $artigo->neolabx ? 'text-success glyphicon-ok' : 'text-danger glyphicon-remove' }}"></span>
            </td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.blog.artigos.destroy', $artigo->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.blog.artigos.edit', $artigo->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection